.Dd
.Dt RF-MK 1
.Os
.\"
.\"
.Sh NAME
.Nm rf-mk
.Nd include files for
.Xr make 1
.\"
.\"
.Sh DESCRIPTION
There are many files that each do something.
Default values for variables are listed in brackets.
.Pp
Variables that may be useful to define globally have a name like
.Ql RF<filename>.* .
For example,
.Ql RFLIB.prof
controls whether to build/install the profiled versions of libraries.
These are like NetBSD's
.Ql MK*
variables.
.\"
.\"
.Sh rf/init.mk
This file is included from most others.
It includes the files
.Pa Makefile.local ,
.Pa ../Makefile.inc ,
and ${MAKECONF} \(em typically
.Pa /etc/rf-mk.conf .
.Pp
Then, it includes a few other files that are only separated
for organizational purposes.
.Pp
They are:
.\"
.Ss rf/init/own.mk
Sets default values for globally useful variables and flags,
and defines some useful shell functions.
.Pp
The following variables are available:
.Bl -tag -width Ds -offset 3n
.It RF.verbose [2]
Controls output verbosity.
.Bl -tag -width 2n -compact
.It 0:
Minimal output.
.It 1:
Describe what is occurring with ${RFPRINT}.
.It 2:
Normal output.
.It 3:
Ignore the effect of the
.Dq @
prefix in make commands,
as if
.Xr make 1
was invoked with
.Fl dl .
.It 4:
Trace shell commands with the shell's
.Fl x
flag,
as if
.Xr make 1
was invoked with
.Fl dx .
.El
.It RFPRINT [echo '# ']
Command used to describe what is happening.
It is used like
.Xr echo 1 .
.El
.\"
.Ss rf/init/pkg.mk
Defines variables that are typically passed to the build with
.In rf/conf.mk .
.Pp
The following variables are available:
.Bl -tag -width Ds -offset 3n
.It PKGVARS
List of variables related to the package name and version.
You cannot change this, but it is documented for completeness.
.It PKG [junkpkg]
Name of the package.
It should theoretically be globally unique.
.It VER [0]
Package version.
.It PKGDIRNAME [${PKG}]
Used in constructing
.Dq personal
directories for your package to use.
It may commonly be set to
.Ql ${PKG}-${VER} .
.It PKGDISTNAME [${PKG}-${VER}]
Filename to distribute the package as.
.It PREFIXVARS
List of variables used to configure where things get installed to,
and where compiled programs look for files.
You cannot change this, but it is documented for completeness.
It includes the following variables.
.It PREFIX [/usr/local]
Convenient variable used
.Sy only
for constructing default values of EXECBASE, FILEBASE, ETCBASE, and VARBASE.
However, the prefixes
.Pa /
and
.Pa /usr
are handled specially, see the code for this.
.Bf Sy
Do not look for files relative to PREFIX.
.Ef
.El
.Pp
EXECBASE:
.Bl -tag -width Ds -offset 3n
.It EXECBASE [${PREFIX}]
Base directory for binaries and libraries.
Everything here may be architecture-dependent.
.It BINDIR [${EXECBASE}/bin]
Normal binaries and scripts.
.It SBINDIR [${EXECBASE}/sbin]
Executables not typically used by a regular user,
typically for system administration.
.It LIBDIR [${EXECBASE}/lib]
Libraries.
.It LIBEXECDIR [${EXECBASE}/libexec/${PKGDIRNAME}]
Helper executables that are not meant to be executed directly by users.
.It LIBDATADIR [${EXECBASE}/libdata/${PKGDIRNAME}]
Static data files.
This is largely interchangeable with ${SHAREDIR},
except they are allowed to be machine-dependent.
This includes firmware.
.El
.Pp
FILEBASE:
.Bl -tag -width Ds -offset 3n
.It FILEBASE [${PREFIX}]
Base directory for static data/files.
.It DOCDIR [${FILEBASE}/share/doc/${PKG}]
Misc documentation files.
.It EXAMPLESDIR [${FILEBASE}/share/examples/${PKG}]
Example files.
.It INCDIR [${FILEBASE}/include]
C include files.
.It MANDIR [${FILEBASE}/share/man]
Man pages.
.It SHAREDIR [${FILEBASE}/share/${PKG}]
Static, architecture-independent data files.
.El
.Pp
ETCBASE:
.Bl -tag -width Ds -offset 3n
.It ETCBASE [${PREFIX}/etc]
Base directory for configuration files.
It may commonly be set to
.Pa /etc .
.It ETCDIR [${ETCBASE}]
Configuration file directory.
It may be set to
.Ql ${ETCBASE}/${PKG}
if there are many config files.
.El
.Pp
VARBASE:
.Bl -tag -width Ds -offset 3n
.It VARBASE [${PREFIX}/var]
Base directory for dynamic (variable) data/files.
It may commonly be set to
.Pa /var .
.It CACHEDIR [${VARBASE}/cache/${PKG}]
Cache files.
.It DBDIR [${VARBASE}/db/${PKG}]
Misc dynamic data files.
.It SPOOLDIR [${VARBASE}/spool/${PKG}]
Spool or queue files.
Files here are typically added and removed often and/or grow and shrink often.
.El
.\"
.Ss rf/sys.mk
Defines suffix rules that are used by multiple files.
The following variables are available:
.Bl -tag -width Ds -offset 3n
.It CFLAGS
Per-file additions: CFLAGS.<file>
.br
Flags used for compiling C files.
.It CXXFLAGS
Per-file additions: CXXFLAGS.<file>
.br
Flags used for compiling CXX files.
.It CPPFLAGS
Per-file additions: CPPFLAGS.<file>
.br
C preprocessor flags.
.El
.\"
.Ss rf/targ.mk
Ensures existence of the default targets.
.\"
.\"
.Sh rf/all.mk
Include all
.In rf/*.mk
files except those that would cause conflicts with each other.
.\"
.\"
.Sh rf/cfiles.mk
Like
.In rf/files.mk
but for config files.
You cannot install to a specific directory.
.Ss Targets
.Bl -tag -width Ds
.It configall
Build the configs.
.It configinstall
Install the configs to ${ETCDIR}.
This is not hooked into the main
.Ql all
target.
.It configexampleinstall
Install the configs to ${EXAMPLESDIR}.
This is hooked into the
.Ql all
target.
.El
.Ss Variables
.Bl -tag -width Ds
.It CFILESOWN, CFILESGRP, CFILESMODE, CFILESBUILD
Same as the corresponding variables in
.In rf/files.mk .
.It RFCFILES.exampleinstall [yes]
If yes, install the config files to ${EXAMPLESDIR}.
.El
.\"
.\"
.Sh rf/clean.mk
Cleans up generated files.
.Ss Targets
.Bl -tag -width Ds
.It clean
Remove ${CLEANFILES}.
.It cleandir
Remove ${CLEANDIRFILES}.
.El
.\"
.\"
.Sh rf/conf.mk
Handles build-time configuration.
The point is to make
.Nm
variables accessible to your code and files.
This can be by generating a file that is included by source code,
or by text substitution.
.Ss Variables
.Bl -tag -width Ds
.It CONF.autodep [no]
If yes, try to intelligently make generated files
.Pq e.g. Pa *.o
depend on the generated
build-time config files
.Pq e.g. Pa rfconf.h
so you don't have to worry about specifying it yourself.
.It CONF.vars [${PKGVARS} ${PREFIXVARS}]
.Nm
variables to export.
.It CONF.h [no]
If yes,
define the shell commands to generate the file
.Pa rfconf.h ,
which is a dump of ${CONF.vars}
variables in C header file format using
.Ql #define .
.Pp
The following is an example
.Pa Makefile
that makes
.Pa rfconf.h
capable of being generated.
.Pa rfconf.h
is not hooked into the
.Ql all
target, but you could build it with
.Dq make rfconf.h .
.Pp
.Pa Makefile :
.Bd -literal -offset Ds
CONF.h = yes

\&.include <rf/all.mk>
.Ed
.It CONF.sub []
A list of files to generate by using simple
.Xr sed 1
text substitution to replace
${CONF.vars} variable names with their values.
For each file
.Pa f ,
expect an input file
.Pa ${f}.in
to exist.
In the input file, the variable name must be prefixed by
.Ql RF_
to minimize naming collisions.
For example, you may want to generate a
.Pa blah.sh
that uses
.Nm
variables to look for files.
You could use the following setup:
.Pp
.Pa Makefile :
.Bd -literal -offset Ds
CONF.sub = blah.sh

# use all.mk, not just conf.mk,
# so we get 'clean' target implementation
\&.include <rf/all.mk>
.Ed
.Pp
.Pa blah.sh.in :
.Bd -literal -offset Ds
#!/bin/sh

echo 'config directory is RF_ETCDIR'
.Ed
.Pp
With this setup,
.Pa blah.sh
is capable of being generated.
It is not hooked into the
.Ql all
target, but you could build it with
.Dq make blah.sh .
.Pp
Actually, the input filename prefix and suffix can be configured with
${CONF.sub.file_prefix} and ${CONF.sub.file_suffix},
and the variable prefix and suffix in the input file can be configured with
${CONF.sub.var_prefix} and ${CONF.sub.var_suffix}.
.El
.\"
.\"
.Sh rf/files.mk
Build and install files.
.Ss Targets
.Bl -tag -width Ds
.It filesall
Build the files.
.It filesinstall
Install the files.
.El
.Ss Variables
.Bl -tag -width Ds
.It FILES
List of files to build/install.
.It FILESOWN [${BINOWN}]
Per-file override: FILESOWN.<file>
.br
Owner.
.It FILESGRP [${BINGRP}]
Per-file override: FILESGRP.<file>
.br
Group.
.It FILESMODE [${NONBINMODE}]
Per-file override: FILESMODE.<file>
.br
Mode.
.It FILESDIR [${BINDIR}]
Per-file override: FILESDIR.<file>
.br
Default location to install the files.
.It FILESNAME
Per-file override: FILESNAME.<file>
.br
Name to install each file as.
Defaults to the name of the file.
.It FILESBUILD [no]
Per-file override: FILESBUILD.<file>
.br
If
.Ql yes ,
add each file to CLEANFILES
and expect there to be a rule to build them.
.El
.\"
.\"
.Sh rf/incs.mk
Build and install include files.
.Ss Targets
.Bl -tag -width Ds
.It incsall
Build the files.
.It includes
Install the files.
This is not hooked into the main
.Ql all
target.
.El
.Ss Variables
Identical to
.In rf/files.mk
but with INCS instead of FILES.
.\"
.\"
.Sh rf/lib.mk
Build and install different types of C libraries.
This includes the typical
.Pa *.a
static library,
the
.Pa *_p.a
profiled library,
the
.Pa *_pic.a
PIC library,
and the
.Pa *.so.*
shared library.
.Ss Targets
.Bl -tag -width Ds
.It liball
Build the libraries.
.It libinstall
Install the libraries.
.El
.Ss Variables
.Bl -tag -width Ds
.It LIB
Name of the library.
.It SRCS [${LIB}.c]
Source files.
.It LIBOWN [${BINOWN}]
Owner.
.It LIBGRP [${BINGRP}]
Group.
.It LIBMODE [${BINMODE}]
Mode.
.It SHLIB_MAJOR, SHLIB_MINOR, SHLIB_TEENY
Major, minor, and teeny version numbers of the shared library.
They can also be defined in the file
.Pa shlib_version
with the format:
.Bd -literal -offset 3n
major=1
minor=2
teeny=3
.Ed
.It RFLIB.static [yes]
Build the static library.
.It RFLIB.prof [yes]
Build the profiled library.
.It RFLIB.pic [yes]
Build the pic library.
.It RFLIB.shared [yes]
Build the shared library.
.El
.\"
.\"
.Sh rf/man.mk
Builds and installs man pages.
.Ss Targets
.Bl -tag -width Ds
.It manall
Build the man pages.
.It maninstall
Install the man pages.
.El
.Ss Variables
.Bl -tag -width Ds
.It MAN
List of man pages to build/install.
.It MANNAME
Per-file override: MANNAME.<file>
.br
Name to install each man page as.
.It MANSUBDIR
Subdirectory under ${MANDIR} to install to.
.It MANOWN [${BINOWN}]
Owner.
.It MANOWN [${BINGRP}]
Group.
.It MANOWN [${NONBINMODE}]
Mode.
.El
.\"
.\"
.Sh rf/prog.mk
Builds and installs C programs.
It uses BINOWN, BINGRP, BINMODE, and BINDIR as defined in
.In rf/init/own.mk .
.Ss Targets
.Bl -tag -width Ds
.It progall
Build the programs.
.It proginstall
Install the programs.
.El
.Ss Variables
.Bl -tag -width Ds
.It PROG, PROGS
Program or programs to build, respectively.
You can only specify one of these variables.
.It SRCS [${PROG}.c]
Per-prog override: SRCS.<prog>
.br
Sources.
.It PROGNAME
Per-prog override: PROGNAME.<prog>
.br
Name to install each program as.
.It LDFLAGS
Per-prog additions: LDFLAGS.<prog>
.br
Linker flags.
.It LDADD
Per-prog additions: LDADD.<prog>
.br
Additional linker objects, usually libraries.
.El
.\"
.\"
.Sh rf/subdir.mk
Descend into subdirectories.
.\"
.\"
.Sh FILES
The
.Nm
files are typically installed under
.Pa /usr/share/mk
so
.Xr make 1
can use them.
.\"
.\"
.Sh EXAMPLES
.\"
.\"
.Sh SEE ALSO
.Xr make 1
