.Dd
.Dt RF-MK 1
.Os
.\"
.\"
.Sh NAME
.Nm rf-mk
.Nd include files for
.Xr make 1
.\"
.\"
.Sh DESCRIPTION
There are multiple files that each do something.
.Ss rf.init.mk
Basic initialization tasks.
.\"
.\"
.Sh FILES
The
.Nm
files are typically installed under
.Pa /usr/share/mk
so
.Xr make 1
can use them.
.\"
.\"
.Sh EXAMPLES
.\"
.\"
.Sh SEE ALSO
.Xr make 1
